apiVersion: elasticity.k8s.rainbow-h2020.eu/v1
kind: MigrationElasticityStrategy
metadata:
  name: migration-estrat-sample
  namespace: rainbow-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: custom-stream-sight-slo-controller
  sloOutputParams:
    currSloCompliancePercentage: 80
    tolerance: 10

  stabilizationWindow:
    scaleDownSeconds: 0
    scaleUpSeconds: 0

  staticConfig:
    baseAffinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/test
                operator: In
                values:
                - a1
                - a2
    alternativeAffinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/test2
                operator: In
                values:
                - a1
                - a2
