.rules-default: &rules-default
  rules:
    - changes:
        - go/orchestration/*
    # - if: $CI_MERGE_REQUEST_IID || $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    #   changes:
    #     - ts/*

stages:
  - install_deps
  - build
  - test
  - deploy

image: golang:1.16

variables:
  GOPATH: $CI_PROJECT_DIR/.go

cache: &global_cache
  key:
    files:
      - go/orchestration/go.mod
      - go/orchestration/go.sum
  paths:
    - .go/pkg/mod/
  policy: pull

before_script:
  - mkdir -p .go
  - cd go/orchestration

# The child pipeline needs at minimum one job to run - otherwise the sub-pipeline fails
# See https://gitlab.com/gitlab-org/gitlab/-/issues/218538#note_348724466
run_always:
  stage: install_deps
  before_script:
    - echo "null"
  script:
    - echo "Ensure that pipeline does not fail if no changes were made in ts folder"

install_deps:
  stage: install_deps
  <<: *rules-default
  cache:
    # inherit all global cache settings, but change the policy to pull-push
    <<: *global_cache
    policy: pull-push
  script:
    - go mod download

build:
  stage: build
  <<: *rules-default
  script:
    - make
    - make manifests

# test:
#   stage: test
#   <<: *rules-default
#   script:
#     - go get gotest.tools/gotestsum@v1.7.0
#     - make test
#     - gotestsum --junitfile report.xml --format orchestration
#   artifacts:
#     untracked: false
#     when: always
#     paths:
#       - go/orchestration/report.xml
#     reports:
#       junit: go/orchestration/report.xml
