# Default configuration for the rainbow-scheduler
# To see all possible values or the active configuration of a scheduler, run it with the `--write-config-to` argument.
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
leaderElection:
  leaderElect: false # Leader election requires additional privileges.
  resourceName: rainbow-scheduler
  resourceNamespace: kube-system
# When comparing the rainbow-scheduler with others, we want to make sure that all nodes are scored,
# because some of the schedulers compared against, depend on that.
percentageOfNodesToScore: 100
profiles:
  # - schedulerName: default-scheduler
  - schedulerName: rainbow-scheduler
    # ToDo: Re-enable plugins one-by-one when they are modified to work for synchronous applications.
    # plugins:
    #   # This section is merged with the default configuration, so we do not need to specify the default plugins.
    #   queueSort:
    #     enabled:
    #     - name: RainbowPriorityMqSort
    #     disabled:
    #     - name: "*"
    #   preFilter:
    #     enabled:
    #       - name: RainbowServiceGraph
    #   filter:
    #     enabled:
    #       - name: RainbowLatency
    #   preScore:
    #     enabled:
    #       - name: RainbowPodsPerNode
    #   score:
    #     enabled:
    #       - name: RainbowPodsPerNode
    #         weight: 1
    #       - name: RainbowNodeCost
    #         weight: 1
    #     disabled:
    #       # These could interfere with the RainbowPodsPerNode scoring.
    #       - name: NodeResourcesBalancedAllocation
    #       - name: NodeResourcesLeastAllocated
    #   reserve:
    #     enabled:
    #       - name: RainbowReserve
    #   permit:
    #     enabled:
    #       - name: RainbowAtomicDeployment

