apiVersion: v1
kind: Namespace
metadata:
  name: polaris
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: polaris-cluster-agent-config
  namespace: polaris
data:
  default-polaris-cluster-agent-config.yaml: |
    # polaris-cluster-agent-config.yaml

    # The list of addresses and ports that the cluster-agent should listen on
    # in the format "<IP>:<PORT>"
    # This setting applies only if "operatingMode" is set to "multiCluster".
    #
    # Default: [ "0.0.0.0:8081" ]
    submitPodListenOn:
      - "0.0.0.0:8081"

    # The update interval for the nodes cache in milliseconds.
    #
    # Default: 200
    nodesCacheUpdateIntervalMs: 200

    # The size of the update queue in the nodes cache.
    # The update queue caches watch events that arrive between the update intervals.
    #
    # Default: 1000
    nodesCacheUpdateQueueSize: 1000
